/**
 * Constants for Order Tool
 */

const ORDER_STEPS = {
  IDLE: 'IDLE',
  ORDER_INITIATED: 'ORDER_INITIATED',
  CART_VALIDATED: 'CART_VALIDATED',
  ADDRESS_SELECTED: 'ADDRESS_SELECTED',
  SHIPPING_CALCULATED: 'SHIPPING_CALCULATED',
  PAYMENT_SELECTED: 'PAYMENT_SELECTED',
  SUMMARY_SHOWN: 'SUMMARY_SHOWN',
  ORDER_CREATED: 'ORDER_CREATED'
};

const ORDER_ACTIONS = {
  INITIATE_ORDER: 'initiate_order',
  VALIDATE_CART: 'validate_cart',
  SELECT_ADDRESS: 'select_address',
  CALCULATE_SHIPPING: 'calculate_shipping',
  SELECT_PAYMENT: 'select_payment',
  SHOW_SUMMARY: 'show_summary',
  CONFIRM_ORDER: 'confirm_order',
  CHECK_STATUS: 'check_status'
};

const PAYMENT_METHODS = {
  COD: 'COD',
  VNPAY: 'VNPay'
};

const ORDER_STATUS = {
  PROCESSING: 'Processing',
  SHIPPED: 'Shipped',
  DELIVERED: 'Delivered',
  CANCELLED: 'Cancelled'
};

const DEFAULT_VALUES = {
  SERVICE_FEE: 10000,
  DEFAULT_SHIPPING_FEE: 29000,
  MIN_WEIGHT: 500,
  DEFAULT_PRODUCT_WEIGHT: 500,
  ESTIMATED_DELIVERY_DAYS: 3
};

module.exports = {
  ORDER_STEPS,
  ORDER_ACTIONS,
  PAYMENT_METHODS,
  ORDER_STATUS,
  DEFAULT_VALUES
};
